import React from 'react';
import ReactMarkdown from 'react-markdown';

interface SummaryViewProps {
  summary: string;
}

export const SummaryView: React.FC<SummaryViewProps> = ({ summary }) => {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="bg-gradient-to-r from-indigo-600 to-violet-600 px-6 py-4 flex items-center justify-between">
        <h2 className="text-white font-semibold text-lg flex items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-5 h-5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25H12" />
          </svg>
          Document Summary
        </h2>
        <span className="text-indigo-100 text-xs bg-white/20 px-2 py-1 rounded">
          AI Generated
        </span>
      </div>
      <div className="p-8 prose prose-indigo max-w-none prose-headings:font-bold prose-h3:text-indigo-700 prose-a:text-indigo-600 text-black">
        <ReactMarkdown>{summary}</ReactMarkdown>
      </div>
      <div className="bg-gray-50 px-6 py-3 border-t border-gray-100 text-xs text-gray-400 text-center">
        Generated by DocuSum AI • Content relies on Gemini 2.5 Flash
      </div>
    </div>
  );
};